version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "09:00"
    timezone: Europe/London
  ignore:
  - dependency-name: serverless
    versions:
    - 2.20.1
    - 2.21.1
    - 2.22.0
    - 2.23.0
    - 2.25.2
    - 2.28.0
    - 2.28.7
    - 2.29.0
    - 2.30.3
    - 2.31.0
    - 2.33.1
    - 2.35.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: mongodb-memory-server
    versions:
    - 6.9.3
  - dependency-name: lodash
    versions:
    - 4.17.20
