language: node_js
node_js:
  - "8"
before_install:
  - npm i -g npm@6
cache:
  directories:
    - node_modules
deploy:
  provider: script
  script: npx sls deploy --stage=test --region=eu-west-2
  on:
    branch: travis-deploy
