language: node_js
node_js:
  - "8"
before_install:
  - npm i -g npm@6
cache:
  directories:
    - node_modules
    # Cache mongo binary installed by mongodb-memory-server
    - $HOME/.mongodb-binaries
deploy:
  provider: script
  script: scripts/deploy
  skip_cleanup: true
  on:
    branch: master
