service: past-grants-search

provider:
  name: aws
  runtime: nodejs8.10
  stage: test
  region: eu-west-2

functions:
  app:
    handler: index.handler
    timeout: 30 # in seconds
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

package:
  excludeDevDependencies: false
  exclude:
    - .*
    - .git/**
    - scripts/**
    - test/**

plugins:
  - serverless-offline
  - serverless-domain-manager

custom:
  stage: ${opt:stage, self:provider.stage}
  serverless-offline:
    port: 8888
  domains:
    prod: lambda.blf.digital
    test: test-lambda.blf.digital
  customDomain:
    basePath: 'past-grants-search'
    domainName: ${self:custom.domains.${self:custom.stage}}
    stage: '${self:custom.stage}'
    createRoute53Record: true
