service: past-grants-search

provider:
  name: aws
  runtime: nodejs8.10
  stage: test
  region: eu-west-2

functions:
  app:
    handler: index.handler
    timeout: 30 # in seconds
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

package:
  exclude:
    - .*
    - .git/**
    - scripts/**
    - test/**
    - node_modules/**
  include:
    - node modules/.bin/**
    - node modules/.cache/**
    - node modules/@types/**
    - node modules/accepts/**
    - node modules/ajv/**
    - node modules/array-flatten/**
    - node modules/asn1/**
    - node modules/assert-plus/**
    - node modules/asynckit/**
    - node modules/aws-sign2/**
    - node modules/aws4/**
    - node modules/bcrypt-pbkdf/**
    - node modules/bl/**
    - node modules/body-parser/**
    - node modules/bson/**
    - node modules/bytes/**
    - node modules/caseless/**
    - node modules/combined-stream/**
    - node modules/content-disposition/**
    - node modules/content-type/**
    - node modules/cookie/**
    - node modules/cookie-signature/**
    - node modules/core-util-is/**
    - node modules/dashdash/**
    - node modules/delayed-stream/**
    - node modules/denque/**
    - node modules/depd/**
    - node modules/destroy/**
    - node modules/dictionary-cy-gb/**
    - node modules/dictionary-en-gb/**
    - node modules/dotenv/**
    - node modules/ecc-jsbn/**
    - node modules/ee-first/**
    - node modules/encodeurl/**
    - node modules/escape-html/**
    - node modules/etag/**
    - node modules/express/**
    - node modules/extend/**
    - node modules/extsprintf/**
    - node modules/fast-deep-equal/**
    - node modules/fast-json-stable-stringify/**
    - node modules/finalhandler/**
    - node modules/forever-agent/**
    - node modules/form-data/**
    - node modules/forwarded/**
    - node modules/fresh/**
    - node modules/getpass/**
    - node modules/har-schema/**
    - node modules/har-validator/**
    - node modules/http-errors/**
    - node modules/http-signature/**
    - node modules/iconv-lite/**
    - node modules/inherits/**
    - node modules/ipaddr.js/**
    - node modules/is-typedarray/**
    - node modules/isarray/**
    - node modules/isstream/**
    - node modules/jsbn/**
    - node modules/json-schema/**
    - node modules/json-schema-traverse/**
    - node modules/json-stringify-safe/**
    - node modules/jsprim/**
    - node modules/lodash/**
    - node modules/media-typer/**
    - node modules/memory-pager/**
    - node modules/merge-descriptors/**
    - node modules/methods/**
    - node modules/mime/**
    - node modules/mime-db/**
    - node modules/mime-types/**
    - node modules/moment/**
    - node modules/mongodb/**
    - node modules/negotiator/**
    - node modules/nspell/**
    - node modules/oauth-sign/**
    - node modules/on-finished/**
    - node modules/on-headers/**
    - node modules/parseurl/**
    - node modules/path-to-regexp/**
    - node modules/performance-now/**
    - node modules/process-nextick-args/**
    - node modules/proxy-addr/**
    - node modules/psl/**
    - node modules/punycode/**
    - node modules/qs/**
    - node modules/range-parser/**
    - node modules/raw-body/**
    - node modules/request/**
    - node modules/request-promise-core/**
    - node modules/request-promise-native/**
    - node modules/require_optional/**
    - node modules/safe-buffer/**
    - node modules/safer-buffer/**
    - node modules/saslprep/**
    - node modules/send/**
    - node modules/serve-static/**
    - node modules/server-timings/**
    - node modules/serverless-http/**
    - node modules/setprototypeof/**
    - node modules/sparse-bitfield/**
    - node modules/sshpk/**
    - node modules/statuses/**
    - node modules/stealthy-require/**
    - node modules/toidentifier/**
    - node modules/tunnel-agent/**
    - node modules/tweetnacl/**
    - node modules/type-is/**
    - node modules/unpipe/**
    - node modules/uri-js/**
    - node modules/util-deprecate/**
    - node modules/utils-merge/**
    - node modules/vary/**
    - node modules/verror/**

plugins:
  - serverless-offline
  - serverless-domain-manager

custom:
  stage: ${opt:stage, self:provider.stage}
  serverless-offline:
    httpPort: 8888
    noPrependStageInUrl: true
  domains:
    prod: lambda.blf.digital
    test: test-lambda.blf.digital
  customDomain:
    basePath: 'past-grants-search'
    domainName: ${self:custom.domains.${self:custom.stage}}
    stage: '${self:custom.stage}'
    createRoute53Record: true
