#!/usr/bin/env node
'use strict';

require('dotenv').config();
const { connectToMongo } = require('../lib/mongo');
const indices = require('../lib/indices');

const createIndices = async () => {
    const { collection } = await connectToMongo();
    indices.forEach(i => {
        collection.createIndex(i.spec, i.options);
    });
    console.log('Indices were created');
    process.exit(1);
};

createIndices();
