#!/usr/bin/env bash

BACKUP_DIR=$1
COLLECTION_NAME=$2

if [ -z "$1" ]
  then
    echo "First argument should be a path to a backup directory"
    exit 1
fi

if [ -z "$2" ]
  then
    echo "Second argument should be the name of the local collection to back up"
    exit 1
fi

mongodump --db blf --collection "$COLLECTION_NAME" --out "$BACKUP_DIR"

echo "Dump completed!"
echo "To upload this export to the remote Mongo instance, use the following command:"
echo ""
echo "./scripts/import-remote \"list,of,hostnames\"" $BACKUP_DIR "local-collection_name" "new-collection-name"
