#!/bin/bash
set -e

INPUT_JSON=$1
DATABASE_NAME=$2
COLLECTION_NAME=$3

export MONGO_URL=mongodb://localhost:27017
export MONGO_DB=$DATABASE_NAME
export MONGO_COLLECTION=$COLLECTION_NAME

# Create indices so the upsert isn't deathly slow
echo "Creating indices..."
./scripts/create-indices

echo "Indices created. Now importing data..."

# Upsert the data by the id field to keep duplicates out
mongoimport -d "$DATABASE_NAME" -c "$COLLECTION_NAME" --type json --file "$INPUT_JSON" --mode upsert --upsertFields id
