#!/bin/bash
set -e

INPUT_CSV=$1
DATABASE_NAME=$2
COLLECTION_NAME=$3

if [ -z "$1" ]
  then
    echo "First argument should be a CSV path"
    exit 1
fi

if [ -z "$2" ]
  then
    echo "Second argument should be the database to use"
    exit 1
fi

if [ -z "$3" ]
  then
    echo "Third argument should be a collection name to import into"
    exit 1
fi

# 1. Parse CSV => JSON
echo "Parsing CSV grant data into JSON...";
echo "Using file $INPUT_CSV"
$(npm bin)/csv-parser "$INPUT_CSV" -o tmp-parsed.json;
echo "Done.";

# 2. Clean data into GrantNav format
./scripts/clean-grant-data -f tmp-parsed.json -o tmp-clean.json --filename $INPUT_CSV;

# 3. Import cleaned JSON into Mongo
echo "Finished cleaning $INPUT_CSV data"
echo "Importing grant data into '$COLLECTION_NAME' collection in database '$DATABASE_NAME'";
./scripts/import-grants tmp-clean.json "$DATABASE_NAME" "$COLLECTION_NAME";

# 4. Cleanup
rm tmp-parsed.json tmp-clean.json;
echo "Cleanup complete";
echo "CSV import successful!";
