#!/usr/bin/env bash

HOSTNAMES=$1
BACKUP_DIR=$2
SRC_COLL=$3
DEST_COLL=$4

if [ -z "$1" ]
  then
    echo "First argument should be a list of hostnames, eg."
    echo "foo-shard-0/dbname-shard-00-00-host.net:port,dbname-shard-00-01-host.net:port,dbname-shard-00-02-host.net:port"
    exit 1
fi

if [ -z "$2" ]
  then
    echo "Second argument should be a path to a backup directory"
    exit 1
fi

if [ -z "$3" ]
  then
    echo "Third argument should be the name of the local collection in the backup directory"
    exit 1
fi

if [ -z "$4" ]
  then
    echo "Fourth argument should be the desired name of the new remote collection"
    exit 1
fi

SOURCE_COLLECTION=blf.$SRC_COLL
DEST_COLLECTION=blf.$DEST_COLL

mongorestore --host "$HOSTNAMES" --ssl --sslAllowInvalidHostnames --username biglotteryfund --authenticationDatabase admin --nsInclude 'blf.*' --nsFrom $SOURCE_COLLECTION --nsTo $DEST_COLLECTION "$BACKUP_DIR"

echo "Import successful! Now go and check the data is correct, and cut over to the new collection ($DEST_COLLECTION)"
