#!/usr/bin/env bash

HOSTNAMES=$1
BACKUP_DIR=$2
TMP_NAME=$3

if [ -z "$1" ]
  then
    echo "First argument should be a list of hostnames, eg."
    echo "foo-shard-0/dbname-shard-00-00-host.net:port,dbname-shard-00-01-host.net:port,dbname-shard-00-02-host.net:port"
    exit 1
fi

if [ -z "$2" ]
  then
    echo "Second argument should be a path to a backup directory"
    exit 1
fi

if [ -z "$3" ]
  then
    echo "Third argument should be a name for the newly-created database"
    exit 1
fi

DEST_COLLECTION=blf.$TMP_NAME

mongorestore --host "$HOSTNAMES" --ssl --sslAllowInvalidHostnames --username biglotteryfund --authenticationDatabase admin --nsInclude 'blf.*' --nsFrom 'blf.grants' --nsTo $DEST_COLLECTION "$BACKUP_DIR"

echo "Import successful! Now go and check the data is correct, and cut over to the new collection ($DEST_COLLECTION)"
